# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Ken Kutyn
title: Solutions Consultant | Product Manager | Experimenter | Builder
email: kennethkutyn@gmail.com
# email_title: Email (Email title override)
phone: 
# phone_title: Phone (Phone title override)
website: 
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: kennethmarshall
github_username:  kennethkutyn
stackoverflow_username: 
dribbble_username: 
facebook_username: 
flickr_username: 
instagram_username: 
linkedin_username: kennethkutyn
xing_username: 
pinterest_username: 
youtube_username: 
orcid_username: 
googlescholar_username: 

# Additional icon links
additional_links:
- title: 
  icon: 
  url: 
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  SOLUTIONS CONSULTING: 12 years experience as an SC (8 in B2B SaaS), 2 time President’s Club winner, 5
  within-company promotions, developed and launched a SaaS app for solutions consultants 
  
  BUSINESS APTITUDE: MBA degree, experience in value consulting engagements
  
  LEADERSHIP: Mentored 4 aspiring presales professionals through PreSales Collective, completed Amplitude Leadership Development Program, onboarded and coached junior SC colleagues
  
  INTERNATIONAL EXPERIENCE: Lived and worked in Canada, UK, USA, Netherlands and Singapore; mapped to AEs covering 26+ countries
  
  DOMAIN EXPERTISE: 6 years experience selling analytics, experimentation, feature flagging and personalization to Product, Data and Engineering teams; acted as Product Lead at 2 early stage start-ups; spoke at 8+ conferences and panels on product management and experimentation


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Deckbuildr
        link: www.deckbuildr.io
        link_text: deckbuildr.io
        additional_links:
        quote: >
        description: | # this will include new lines to allow paragraphs
            I co-founded a microSaaS that enables sales people to quickly generate a custom pitch deck for an upcoming customer meeting. 
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Rightly
        link: www.rightly.co.uk
        link_text: rightly.co.uk
        additional_links:
        quote: >
        description: | # this will include new lines to allow paragraphs
            I was founding PM for a personal data startup enabling EU data citizens to protect their rights according to GDPR. We obtained seed and Series A funding before I transitioned to an advisor role.  
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: PreSales Collective
        link: 
        link_text: 
        additional_links:
        quote: >
        description: | # this will include new lines to allow paragraphs
            Mentored 4 early-career professionals to transition into presales, supporting their coursework and providing coaching and guidance on presales competencies and the job search. PreSales Academy and PreSales Foundations put a special emphasis on making tech jobs accessible to diverse backgrounds 
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Toast Masters - Competent Communicator
        link: 
        link_text: 
        additional_links:
        quote: >
        description: | # this will include new lines to allow paragraphs
            Public speaking certificate issued by Toastmasters International for successful completion of ten prepared speeches.
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Amplitude
        sub_title: Senior Solutions Consultant
        caption: Feb 2021 to present
        link: www.amplitude.com
        quote: >
        description: | # this will include new lines to allow paragraphs
          Worked with Product, PMM, Sales, Marketing and Enablement on GTM strategy for launch of Experiment. Enabled SCs on Experiment through training, playbooks, templates and 1:1 deal coaching sessions. As the senior SC in the EMEA North and APJ regions, acted as a mentor to junior colleagues and a key partner to sales leadership on deal strategy.
      - layout: right
        title: Optimizely
        sub_title: Lead Solutions Consultant
        caption: Dec 2016 to Jan 2021
        link: www.optimizely.com
        quote: >
        description: | # this will include new lines to allow paragraphs
          Guided customers and prospects through technical validation of Optimizely’s client-side and server-side feature flagging and experimentation platforms, including PoCs, workshops, and demos. Partnered with sales leadership to drive deal strategy and forecasting accuracy. Attached to greater than $6M in ARR over first 3 years. Received rapid promotions to Senior and Lead Solutions Engineer in first 3 years. Qualified for President’s Club twice as top SC in region.
      - layout: right
        title: Oracle
        sub_title: Staff Solutions Consultant
        caption: April 2014 to October 2015
        link: www.oracle.com
        quote: >
        description: | # this will include new lines to allow paragraphs
          Assisted Oracle customers in transitioning from traditional on-premises BI and Analytics, to a modern cloud-based platform. Acted as a leader for sales team, including running numerous internal trainings for Account Executives on the benefits of cloud technology.
      - layout: right
        title: S-FRAME Software
        sub_title: Senior Application Engineer
        caption: April 2014 to October 2015
        link: www.oracle.com
        quote: >
        description: | # this will include new lines to allow paragraphs
          Owned customer-facing activities for Vancouver office, including pre-sales, onboarding, success, and support. Opened satellite office in London and took responsibility for all go to market strategy and operations.
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Maastricht School of Management
        sub_title: Master's of Business Administration
        caption: 2018-2020
        quote: 
        description:  # this will include new lines to allow paragraphs
      - layout: top-right
        title: University of British Columbia
        sub_title: Bachelor of Applied Science (Civil Engineering)
        caption: 2007-2011
        quote: 
        description:  # this will include new lines to allow paragraphs
 
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]

